import Link from 'next/link';
import { Logo } from '@/components/logo';

export const metadata = {
  title: 'Privacy Policy – Courtio',
};

const LAST_UPDATED = 'June 8, 2025';
const CONTACT_EMAIL = 'privacy@courtio.app';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-background/80 backdrop-blur border-b border-border">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/sign-in">
            <Logo size="sm" />
          </Link>
          <span className="text-xs text-muted-foreground">Last updated {LAST_UPDATED}</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10 space-y-10">
        <div>
          <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
          <p className="text-muted-foreground">
            This policy describes what data Courtio collects, why, and how it is stored and
            protected. Courtio is a volleyball tournament platform. By creating an account you
            accept this policy.
          </p>
        </div>

        <Section title="1. Who we are">
          <p>
            Courtio (&quot;we&quot;, &quot;us&quot;) operates the platform accessible at{' '}
            <span className="text-primary">app.courtio.online</span>. For any privacy-related
            question contact us at{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        <Section title="2. Data we collect">
          <Subsection title="Account data (via Clerk)">
            <p>
              We use <strong>Clerk</strong> for authentication. When you sign up or sign in,
              Clerk collects and processes:
            </p>
            <ul className="list-disc list-inside space-y-1">
              <li>Email address</li>
              <li>Full name and profile picture (from OAuth providers if used)</li>
              <li>Authentication method (email/password, Google, etc.)</li>
              <li>Session tokens and device identifiers stored in browser cookies</li>
            </ul>
            <p>
              Clerk acts as a data processor on our behalf. Their privacy policy is available at{' '}
              <a
                href="https://clerk.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline"
              >
                clerk.com/privacy
              </a>
              .
            </p>
          </Subsection>

          <Subsection title="Profile and app data">
            <p>We store in our own database (MongoDB):</p>
            <ul className="list-disc list-inside space-y-1">
              <li>Your Clerk user ID (used to link your account to app data)</li>
              <li>Volleyball roles and positions you configure on your profile</li>
              <li>Teams you belong to and your role within each team (player, captain)</li>
              <li>Tournament registrations — individual or as a team</li>
              <li>Notifications generated by platform activity (e.g. new tournaments)</li>
            </ul>
          </Subsection>

          <Subsection title="Images (via Cloudinary)">
            <p>
              Profile pictures and team logos you upload are stored on{' '}
              <strong>Cloudinary</strong>, a cloud media service. Cloudinary&apos;s privacy
              policy is at{' '}
              <a
                href="https://cloudinary.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline"
              >
                cloudinary.com/privacy
              </a>
              .
            </p>
          </Subsection>

          <Subsection title="Location data (via Mapbox)">
            <p>
              Tournament pages may display maps powered by <strong>Mapbox</strong>. If you
              interact with a map, Mapbox may receive your approximate location or IP address.
              Mapbox&apos;s privacy policy is at{' '}
              <a
                href="https://www.mapbox.com/legal/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline"
              >
                mapbox.com/legal/privacy
              </a>
              .
            </p>
          </Subsection>

          <Subsection title="Push notifications">
            <p>
              If you grant notification permission, your browser generates a push subscription
              (an endpoint URL and encryption keys). This subscription is stored in our database
              and is used only to deliver tournament notifications to you. It is not shared with
              third parties. You can revoke permission at any time in your browser settings,
              which stops all future pushes.
            </p>
          </Subsection>
        </Section>

        <Section title="3. How we use your data">
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong>Authentication</strong> — to verify your identity and keep your session
              secure.
            </li>
            <li>
              <strong>Platform features</strong> — to display teams, rosters, tournaments, and
              registrations.
            </li>
            <li>
              <strong>Notifications</strong> — to alert you when new tournaments are created or
              when a tournament is filling up.
            </li>
            <li>
              <strong>Administration</strong> — platform administrators can view user accounts
              and team/tournament data for moderation purposes.
            </li>
          </ul>
          <p>
            We do not sell your data. We do not use your data for advertising. We do not use
            automated profiling or decision-making.
          </p>
        </Section>

        <Section title="4. Cookies and local storage">
          <p>
            Clerk sets session cookies required for authentication. These are strictly necessary
            and cannot be declined while using the platform. We do not set any marketing or
            analytics cookies.
          </p>
        </Section>

        <Section title="5. Data retention">
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong>Account data</strong> — retained as long as your account exists. Deleting
              your Clerk account removes your authentication data from Clerk&apos;s systems.
            </li>
            <li>
              <strong>App data</strong> — your profile, team memberships, and tournament history
              are kept until you request deletion.
            </li>
            <li>
              <strong>Push subscriptions</strong> — automatically removed when a push delivery
              fails with a &quot;gone&quot; response from the browser, or when you revoke
              permission.
            </li>
            <li>
              <strong>Notifications</strong> — stored in our database, never automatically
              purged. You can mark them read within the app.
            </li>
          </ul>
        </Section>

        <Section title="6. Your rights (GDPR)">
          <p>
            If you are located in the European Union or European Economic Area, you have the
            right to:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong>Access</strong> — request a copy of the personal data we hold about you.
            </li>
            <li>
              <strong>Rectification</strong> — correct inaccurate data.
            </li>
            <li>
              <strong>Erasure</strong> — request deletion of your data (&quot;right to be
              forgotten&quot;).
            </li>
            <li>
              <strong>Portability</strong> — receive your data in a structured, machine-readable
              format.
            </li>
            <li>
              <strong>Objection</strong> — object to processing where our basis is legitimate
              interest.
            </li>
          </ul>
          <p>
            To exercise any of these rights, email{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
              {CONTACT_EMAIL}
            </a>
            . We will respond within 30 days.
          </p>
        </Section>

        <Section title="7. Security">
          <p>
            All data is transmitted over HTTPS. Passwords are never stored by us — they are
            managed exclusively by Clerk using industry-standard hashing. Push subscription keys
            are stored encrypted in our database and used only for their intended delivery
            purpose.
          </p>
        </Section>

        <Section title="8. Changes to this policy">
          <p>
            We may update this policy. The &quot;Last updated&quot; date at the top reflects the
            most recent revision. Continued use of Courtio after a change constitutes acceptance
            of the updated policy.
          </p>
        </Section>

        <div className="border-t border-border pt-6 text-sm text-muted-foreground">
          Questions? Contact{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
            {CONTACT_EMAIL}
          </a>
          .
        </div>
      </main>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-foreground">{title}</h2>
      <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">{children}</div>
    </section>
  );
}

function Subsection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <h3 className="text-sm font-semibold text-foreground">{title}</h3>
      <div className="space-y-2 pl-3 border-l border-border">{children}</div>
    </div>
  );
}
